stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  image: openjdk:11-jdk-slim
  before_script:
    - apt-get update && apt-get install -y maven
  script:
    - mvn clean compile

test:
  stage: test
  image: openjdk:11-jdk-slim
  before_script:
    - apt-get update && apt-get install -y maven
  script:
    - mvn test -Dtest=GitLabCICDTest